import { createFileRoute, Link } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";
import { ArrowLeft, FileText, Mail, Instagram, Twitter, Linkedin } from "lucide-react";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — CabbageCode" },
      {
        name: "description",
        content:
          "Review the Terms of Service for CabbageCode AI Client Finder & Website Audit Automation. Read our agreement protocols.",
      },
      { property: "og:title", content: "Terms of Service — CabbageCode" },
      {
        property: "og:description",
        content: "Read the Terms of Service for the CabbageCode workspace CRM platform.",
      },
    ],
  }),
  component: TermsOfService,
});

function TermsOfService() {
  return (
    <div className="min-h-screen relative overflow-hidden flex flex-col">
      {/* Background decorations matching the landing page */}
      <div className="absolute inset-0 bg-background pointer-events-none -z-20" />
      <div className="absolute top-[-20%] left-[-20%] w-[60%] h-[60%] rounded-full bg-primary/5 blur-[120px] pointer-events-none -z-10 animate-pulse duration-10000" />
      <div className="absolute bottom-[-20%] right-[-20%] w-[60%] h-[60%] rounded-full bg-success/5 blur-[120px] pointer-events-none -z-10" />

      {/* Header */}
      <header className="relative z-10 max-w-4xl mx-auto w-full flex items-center justify-between px-6 py-5">
        <Link to="/" className="flex items-center">
          <img
            src="/logo.png"
            alt="Logo"
            className="h-12 w-auto max-w-full object-contain rounded-xl"
          />
        </Link>
        <Link to="/">
          <Button variant="ghost" className="gap-2">
            <ArrowLeft className="h-4 w-4" /> Back to Home
          </Button>
        </Link>
      </header>

      {/* Content */}
      <main className="flex-grow max-w-3xl mx-auto px-6 py-12 relative z-10">
        <div className="glass rounded-3xl p-8 md:p-12 space-y-8 border border-border/40 shadow-2xl">
          <div className="flex items-center gap-3.5 border-b border-border/20 pb-6">
            <div className="h-12 w-12 rounded-2xl bg-primary/10 text-primary grid place-items-center">
              <FileText className="h-6 w-6" />
            </div>
            <div>
              <h1 className="text-3xl font-bold tracking-tight text-foreground">Terms of Service</h1>
              <p className="text-xs text-muted-foreground mt-1">Last Updated: July 2, 2026</p>
            </div>
          </div>

          <div className="space-y-6 text-sm leading-relaxed text-muted-foreground">
            <p>
              By accessing and using CabbageCode, you acknowledge and agree to comply with the terms,
              conditions, and guidelines listed below. If you do not accept these conditions, you may
              not use the auditing services or workspace CRM tools.
            </p>

            <section className="space-y-3">
              <h2 className="text-lg font-semibold text-foreground">1. Acceptance of terms</h2>
              <p>
                CabbageCode provides local business search, AI audit scores, templates, and pipeline
                management features. All services are subject to operational rates, API constraints,
                and these terms of service. We reserve the right to refine these policies at any time.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-lg font-semibold text-foreground">2. Responsible Auditing & Usage</h2>
              <p>
                You agree to query data responsibly. Automated mapping searches and website scans should
                conform to fair usage thresholds. Scraping our internal API or attempts to overload the
                lead discovery services may result in temporary or permanent suspension of your workspace.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-lg font-semibold text-foreground">3. Lead Communication & Compliance</h2>
              <p>
                Outreach templates generated by CabbageCode are recommendations only. You are solely
                responsible for reviewing the accuracy, compliance, and messaging of any communication
                before dispatching. You must adhere to anti-spam legal frameworks (e.g. CAN-SPAM, GDPR)
                applicable in your region.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-lg font-semibold text-foreground">4. Limitation of Liability</h2>
              <p>
                CabbageCode retrieves public listing records and evaluates website metrics via AI agents.
                We make no absolute guarantee regarding the accuracy of third-party data, lead response rates,
                or sales conversions. The services are provided "as-is" without warranty.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-lg font-semibold text-foreground">5. Owner & Contact Information</h2>
              <p>
                If you have questions, feedback, or need clarification regarding these Terms of Service,
                please contact Sujeet Vishwakarma via any of the options below:
              </p>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3.5 mt-3">
                <a
                  href="mailto:sujeet.cabbagecode@gmail.com"
                  className="flex items-center gap-3 p-3.5 rounded-2xl bg-primary/5 hover:bg-primary/10 border border-border/40 hover:border-primary/30 transition-all text-foreground hover:scale-[1.02]"
                >
                  <div className="h-9 w-9 rounded-xl bg-primary/10 grid place-items-center text-primary">
                    <Mail className="h-5 w-5" />
                  </div>
                  <div className="min-w-0">
                    <p className="text-xs text-muted-foreground">Email</p>
                    <p className="text-sm font-medium truncate">sujeet.cabbagecode@gmail.com</p>
                  </div>
                </a>

                <a
                  href="https://www.instagram.com/cabbage_code/"
                  target="_blank"
                  rel="noreferrer"
                  className="flex items-center gap-3 p-3.5 rounded-2xl bg-primary/5 hover:bg-primary/10 border border-border/40 hover:border-primary/30 transition-all text-foreground hover:scale-[1.02]"
                >
                  <div className="h-9 w-9 rounded-xl bg-primary/10 grid place-items-center text-primary">
                    <Instagram className="h-5 w-5" />
                  </div>
                  <div className="min-w-0">
                    <p className="text-xs text-muted-foreground">Instagram</p>
                    <p className="text-sm font-medium truncate">@cabbage_code</p>
                  </div>
                </a>

                <a
                  href="https://x.com/sujeetv23936479"
                  target="_blank"
                  rel="noreferrer"
                  className="flex items-center gap-3 p-3.5 rounded-2xl bg-primary/5 hover:bg-primary/10 border border-border/40 hover:border-primary/30 transition-all text-foreground hover:scale-[1.02]"
                >
                  <div className="h-9 w-9 rounded-xl bg-primary/10 grid place-items-center text-primary">
                    <Twitter className="h-5 w-5" />
                  </div>
                  <div className="min-w-0">
                    <p className="text-xs text-muted-foreground">Twitter / X</p>
                    <p className="text-sm font-medium truncate">@sujeetv23936479</p>
                  </div>
                </a>

                <a
                  href="https://www.linkedin.com/in/sujeet-vishwakarma-a19b2323a/"
                  target="_blank"
                  rel="noreferrer"
                  className="flex items-center gap-3 p-3.5 rounded-2xl bg-primary/5 hover:bg-primary/10 border border-border/40 hover:border-primary/30 transition-all text-foreground hover:scale-[1.02]"
                >
                  <div className="h-9 w-9 rounded-xl bg-primary/10 grid place-items-center text-primary">
                    <Linkedin className="h-5 w-5" />
                  </div>
                  <div className="min-w-0">
                    <p className="text-xs text-muted-foreground">LinkedIn</p>
                    <p className="text-sm font-medium truncate">Sujeet Vishwakarma</p>
                  </div>
                </a>
              </div>
            </section>
          </div>
        </div>
      </main>

      {/* Mini Footer for Terms Page */}
      <footer className="relative border-t border-border/40 py-6 text-center text-xs text-muted-foreground bg-background/20 backdrop-blur-sm mt-auto z-10">
        © {new Date().getFullYear()} CabbageCode. All rights reserved.
      </footer>
    </div>
  );
}
